import { 
  ChakraProvider, 
  ColorModeScript, 
  Container 
} from '@chakra-ui/react';
import { AnimatePresence } from 'framer-motion';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { Navbar, Footer } from '../components';
import { FontProvider } from '../context/FontSize';
import { Fonts, theme } from '../lib';

// import '../styles/carousel.css'

function MyApp({ Component, pageProps, router }: AppProps) {
  const displayFooter = (router.pathname === '/' || router.pathname === '/contact') ? 'none' : 'flex';
  
  return (
    <ChakraProvider theme={theme}>
      <FontProvider>
        <Fonts/>

        <Head>
          <title>Ivus Chua 🏠</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <Navbar/>
          <ColorModeScript initialColorMode={theme.config.initialColorMode} />
          <Container maxW={{base: '95%', md: '80%', lg: '80%'}} textAlign={'start'}>
            <AnimatePresence
              exitBeforeEnter
              initial={true}
              onExitComplete={() => {
                if (typeof window !== 'undefined') {
                  window.scrollTo({ top: 0 })
                }
              }}
            >
              <Component {...pageProps} key={router.route} />
            </AnimatePresence>
          </Container>
        </main>

        <Footer display={displayFooter}/>
      </FontProvider>
    </ChakraProvider>
  )
}

export default MyApp
